config/routes.rb
Rails.application.routes.draw do
  resources :job_titles
  resources :magazines
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'wines#index'
end

app/models/magazine.rb
class Magazine < ApplicationRecord
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: %i[ show edit update destroy ]

  # GET /magazines or /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1 or /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines or /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to magazine_url(@magazine), notice: "Magazine was successfully created." }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1 or /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to magazine_url(@magazine), notice: "Magazine was successfully updated." }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1 or /magazines/1.json
  def destroy
    @magazine.destroy

    respond_to do |format|
      format.html { redirect_to magazines_url, notice: "Magazine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def magazine_params
      params.require(:magazine).permit(:title)
    end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.erb
<%= form_with(model: magazine) do |form| %>
  <% if magazine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
        <% magazine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/magazines/_magazine.html.erb
<div id="<%= dom_id magazine %>">
  <p>
    <strong>Title:</strong>
    <%= magazine.title %>
  </p>

</div>

app/views/magazines/edit.html.erb
<h1>Editing magazine</h1>

<%= render "form", magazine: @magazine %>

<br>

<div>
  <%= link_to "Show this magazine", @magazine %> |
  <%= link_to "Back to magazines", magazines_path %>
</div>

app/views/magazines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Magazines</h1>

<div id="magazines">
  <% @magazines.each do |magazine| %>
    <%= render magazine %>
    <p>
      <%= link_to "Show this magazine", magazine %>
    </p>
  <% end %>
</div>

<%= link_to "New magazine", new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New magazine</h1>

<%= render "form", magazine: @magazine %>

<br>

<div>
  <%= link_to "Back to magazines", magazines_path %>
</div>

app/views/magazines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @magazine %>

<div>
  <%= link_to "Edit this magazine", edit_magazine_path(@magazine) %> |
  <%= link_to "Back to magazines", magazines_path %>

  <%= button_to "Destroy this magazine", @magazine, method: :delete %>
</div>