config/routes.rb
Rails.application.routes.draw do
  resources :job_titles
  resources :magazines
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'wines#index'
end

app/models/job_title.rb
class JobTitle < ApplicationRecord
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  before_action :set_job_title, only: %i[ show edit update destroy ]

  # GET /job_titles or /job_titles.json
  def index
    @job_titles = JobTitle.all
  end

  # GET /job_titles/1 or /job_titles/1.json
  def show
  end

  # GET /job_titles/new
  def new
    @job_title = JobTitle.new
  end

  # GET /job_titles/1/edit
  def edit
  end

  # POST /job_titles or /job_titles.json
  def create
    @job_title = JobTitle.new(job_title_params)

    respond_to do |format|
      if @job_title.save
        format.html { redirect_to job_title_url(@job_title), notice: "Job title was successfully created." }
        format.json { render :show, status: :created, location: @job_title }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_titles/1 or /job_titles/1.json
  def update
    respond_to do |format|
      if @job_title.update(job_title_params)
        format.html { redirect_to job_title_url(@job_title), notice: "Job title was successfully updated." }
        format.json { render :show, status: :ok, location: @job_title }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_titles/1 or /job_titles/1.json
  def destroy
    @job_title.destroy

    respond_to do |format|
      format.html { redirect_to job_titles_url, notice: "Job title was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_title
      @job_title = JobTitle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_title_params
      params.require(:job_title).permit(:job_title)
    end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/views/job_titles/_form.html.erb
<%= form_with(model: job_title) do |form| %>
  <% if job_title.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_title.errors.count, "error") %> prohibited this job_title from being saved:</h2>

      <ul>
        <% job_title.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :job_title, style: "display: block" %>
    <%= form.text_field :job_title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_titles/_job_title.html.erb
<div id="<%= dom_id job_title %>">
  <p>
    <strong>Job title:</strong>
    <%= job_title.job_title %>
  </p>

</div>

app/views/job_titles/edit.html.erb
<h1>Editing job title</h1>

<%= render "form", job_title: @job_title %>

<br>

<div>
  <%= link_to "Show this job title", @job_title %> |
  <%= link_to "Back to job titles", job_titles_path %>
</div>

app/views/job_titles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Job titles</h1>

<div id="job_titles">
  <% @job_titles.each do |job_title| %>
    <%= render job_title %>
    <p>
      <%= link_to "Show this job title", job_title %>
    </p>
  <% end %>
</div>

<%= link_to "New job title", new_job_title_path %>

app/views/job_titles/new.html.erb
<h1>New job title</h1>

<%= render "form", job_title: @job_title %>

<br>

<div>
  <%= link_to "Back to job titles", job_titles_path %>
</div>

app/views/job_titles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_title %>

<div>
  <%= link_to "Edit this job title", edit_job_title_path(@job_title) %> |
  <%= link_to "Back to job titles", job_titles_path %>

  <%= button_to "Destroy this job title", @job_title, method: :delete %>
</div>