config/routes.rb
Rails.application.routes.draw do
  resources :job_titles
  resources :magazines
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'wines#index'
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
  before_action :set_oenologist, only: %i[ show edit update destroy ]

  # GET /oenologists or /oenologists.json
  def index
    @oenologists = Oenologist.all
  end

  # GET /oenologists/1 or /oenologists/1.json
  def show
  end

  # GET /oenologists/new
  def new
    @oenologist = Oenologist.new
  end

  # GET /oenologists/1/edit
  def edit
  end

  # POST /oenologists or /oenologists.json
  def create
    @oenologist = Oenologist.new(oenologist_params)

    respond_to do |format|
      if @oenologist.save
        format.html { redirect_to oenologist_url(@oenologist), notice: "Oenologist was successfully created." }
        format.json { render :show, status: :created, location: @oenologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oenologists/1 or /oenologists/1.json
  def update
    respond_to do |format|
      if @oenologist.update(oenologist_params)
        format.html { redirect_to oenologist_url(@oenologist), notice: "Oenologist was successfully updated." }
        format.json { render :show, status: :ok, location: @oenologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oenologists/1 or /oenologists/1.json
  def destroy
    @oenologist.destroy

    respond_to do |format|
      format.html { redirect_to oenologists_url, notice: "Oenologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oenologist
      @oenologist = Oenologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oenologist_params
      params.require(:oenologist).permit(:name)
    end
end

app/helpers/oenologists_helper.rb
module OenologistsHelper
end

app/views/oenologists/_form.html.erb
<%= form_with(model: oenologist) do |form| %>
  <% if oenologist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(oenologist.errors.count, "error") %> prohibited this oenologist from being saved:</h2>

      <ul>
        <% oenologist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/oenologists/_oenologist.html.erb
<div id="<%= dom_id oenologist %>">
  <p>
    <strong>Name:</strong>
    <%= oenologist.name %>
  </p>

</div>

app/views/oenologists/edit.html.erb
<h1>Editing oenologist</h1>

<%= render "form", oenologist: @oenologist %>

<br>

<div>
  <%= link_to "Show this oenologist", @oenologist %> |
  <%= link_to "Back to oenologists", oenologists_path %>
</div>

app/views/oenologists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Oenologists</h1>

<div id="oenologists">
  <% @oenologists.each do |oenologist| %>
    <%= render oenologist %>
    <p>
      <%= link_to "Show this oenologist", oenologist %>
    </p>
  <% end %>
</div>

<%= link_to "New oenologist", new_oenologist_path %>

app/views/oenologists/new.html.erb
<h1>New oenologist</h1>

<%= render "form", oenologist: @oenologist %>

<br>

<div>
  <%= link_to "Back to oenologists", oenologists_path %>
</div>

app/views/oenologists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @oenologist %>

<div>
  <%= link_to "Edit this oenologist", edit_oenologist_path(@oenologist) %> |
  <%= link_to "Back to oenologists", oenologists_path %>

  <%= button_to "Destroy this oenologist", @oenologist, method: :delete %>
</div>